INSERT INTO series (title, author_id, subgenre_id) VALUES ("title", 1, 1);
INSERT INTO series (title, author_id, subgenre_id) VALUES ("title", 1, 1);
INSERT INTO subgenres (name) VALUES ("name");
INSERT INTO subgenres (name) VALUES ("name");
INSERT INTO authors (name) VALUES ("name");
INSERT INTO authors (name) VALUES ("name");
INSERT INTO books (title, year, series_id) VALUES ("title", 1200, 1);
INSERT INTO books (title, year, series_id) VALUES ("title", 1200, 1);
INSERT INTO books (title, year, series_id) VALUES ("title", 1200, 1);
INSERT INTO books (title, year, series_id) VALUES ("title", 1200, 1);
INSERT INTO books (title, year, series_id) VALUES ("title", 1200, 1);
INSERT INTO books (title, year, series_id) VALUES ("title", 1200, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("name", "species", "motto", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("name", "species", "motto", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("name", "species", "motto", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("name", "species", "motto", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("name", "species", "motto", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("name", "species", "motto", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("name", "species", "motto", 1, 1);
INSERT INTO characters (name, species, motto, series_id, author_id) VALUES ("name", "species", "motto", 1, 1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
INSERT INTO character_books (book_id, character_id) VALUES (1,1);
